Enforce chainId
MetaMask/controllers pull request #324
Opened 2021-01-13 18:35 UTC by estebanmino

This PR makes sure that all custom rpc networks have a valid chainId, and disregard the usage of networkId in favor of chainId

2021-01-15 05:55 UTC, rekmarks requested changes
Overall looks good! Just a few questions and requests.

2021-01-15 14:43 UTC, estebanmino commented on src/network/NetworkController.ts
> +      provider: { type: 'mainnet', chainId: '1' },
true

2021-01-15 14:43 UTC, estebanmino commented on src/transaction/TransactionController.ts
> +      networkID,
yeah, I think that's called that way only because etherscan

2021-01-15 14:44 UTC, estebanmino commented on src/network/NetworkController.ts
> +  rpc = '',
I'll do it

2021-01-15 14:46 UTC, estebanmino commented on src/network/NetworkController.ts
> +  rpc = '',
oh wait, this would need a migration as well

2021-01-15 14:47 UTC, estebanmino commented on src/network/NetworkController.ts
> +  rpc = '',
for transactions, I'd put that together with the work on the tx controller

2021-01-18 20:51 UTC, rekmarks commented on src/network/NetworkController.ts
> +  rpc = '',
We decided to do this in a follow-up.

2021-01-18 21:06 UTC, rekmarks approved these changes
LGTM!

2021-01-19 15:54 UTC, merged